M48
; DRILL file {KiCad (6.0.5)} date Thu Nov 10 06:36:38 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-10T06:36:38+13:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0787
%
G90
G05
T1
X2.7067Y-3.3996
X2.7067Y-3.7343
X2.7067Y-3.9122
X2.7067Y-4.2469
T0
M30
